from .models import Product, Notification
import pytesseract
from PIL import Image
import re

pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

def get_notifications_for_user(user):
    return Notification.objects.filter(user=user, is_read=False).order_by('-timestamp')

def extract_products_from_receipt(image_path):

    # Usa Tesseract per estrarre il testo dall'immagine
    text = pytesseract.image_to_string(Image.open(image_path))
    
    # Dividi il testo in righe
    lines = text.split('\n')
    
    # Lista per conservare i nomi dei prodotti
    products = []

    # Cerca di estrarre i nomi dei prodotti dalle righe
    for line in lines:
        # Usa espressioni regolari per trovare nomi di prodotti
        # Adatta questo pattern in base alla struttura degli scontrini
        match = re.match(r'^[a-zA-Z\s]+$', line)
        if match:
            product_name = line.strip().capitalize()
            products.append(product_name)

    return products

PRODUCT_CATEGORY_MAP = {
    'apple': 'Fruit',
    'banana': 'Fruit',
    'orange': 'Fruit',
    'grape': 'Fruit',
    'watermelon': 'Fruit',
    'strawberry': 'Fruit',
    'blueberry': 'Fruit',
    'raspberry': 'Fruit',
    'kiwi': 'Fruit',
    'pear': 'Fruit',
    'peach': 'Fruit',
    'plum': 'Fruit',
    'cherry': 'Fruit',
    'mango': 'Fruit',
    'pineapple': 'Fruit',
    'lemon': 'Fruit',
    'lime': 'Fruit',
    'grapefruit': 'Fruit',
    'tomato': 'Vegetable',
    'carrot': 'Vegetable',
    'broccoli': 'Vegetable',
    'cauliflower': 'Vegetable',
    'spinach': 'Vegetable',
    'lettuce': 'Vegetable',
    'kale': 'Vegetable',
    'cabbage': 'Vegetable',
    'celery': 'Vegetable',
    'cucumber': 'Vegetable',
    'zucchini': 'Vegetable',
    'eggplant': 'Vegetable',
    'pepper': 'Vegetable',
    'onion': 'Vegetable',
    'garlic': 'Vegetable',
    'potato': 'Vegetable',
    'sweet potato': 'Vegetable',
    'yam': 'Vegetable',
    'corn': 'Vegetable',
    'pea': 'Vegetable',
    'bean': 'Vegetable',
    'lentil': 'Vegetable',
    'chickpea': 'Vegetable',
    'soybean': 'Vegetable',
    'tofu': 'Vegetable',
    'tempeh': 'Vegetable',
    'mushroom': 'Vegetable',
    'avocado': 'Fruit',
    'bread': 'Bakery',
    'bagel': 'Bakery',
    'croissant': 'Bakery',
    'muffin': 'Bakery',
    'donut': 'Bakery',
    'biscuit': 'Bakery',
    'scone': 'Bakery',
    'tortilla': 'Bakery',
    'rice': 'Grain',
    'pasta': 'Grain',
    'noodle': 'Grain',
    'quinoa': 'Grain',
    'oatmeal': 'Grain',
    'barley': 'Grain',
    'wheat': 'Grain',
    'flour': 'Grain',
    'milk': 'Dairy',
    'cheese': 'Dairy',
    'yogurt': 'Dairy',
    'butter': 'Dairy',
    'cream': 'Dairy',
    'egg': 'Dairy',
    'beef': 'Meat',
    'pork': 'Meat',
    'chicken': 'Meat',
    'turkey': 'Meat',
    'lamb': 'Meat',
    'duck': 'Meat',
    'sausage': 'Meat',
    'bacon': 'Meat',
    'ham': 'Meat',
    'salami': 'Meat',
    'fish': 'Seafood',
    'salmon': 'Seafood',
    'tuna': 'Seafood',
    'shrimp': 'Seafood',
    'crab': 'Seafood',
    'lobster': 'Seafood',
    'clam': 'Seafood',
    'oyster': 'Seafood',
    'scallop': 'Seafood',
    'trout': 'Seafood',
    'cod': 'Seafood',
    'olive oil': 'Condiment',
    'vinegar': 'Condiment',
    'ketchup': 'Condiment',
    'mustard': 'Condiment',
    'mayonnaise': 'Condiment',
    'soy sauce': 'Condiment',
    'hot sauce': 'Condiment',
    'sugar': 'Baking',
    'salt': 'Baking',
    'pepper': 'Spice',
    'cinnamon': 'Spice',
    'nutmeg': 'Spice',
    'ginger': 'Spice',
    'turmeric': 'Spice',
    'basil': 'Herb',
    'parsley': 'Herb',
    'cilantro': 'Herb',
    'rosemary': 'Herb',
    'thyme': 'Herb',
    'oregano': 'Herb',
    'mint': 'Herb',
    'blackberry': 'Fruit',
    'cantaloupe': 'Fruit',
    'fig': 'Fruit',
    'guava': 'Fruit',
    'lychee': 'Fruit',
    'papaya': 'Fruit',
    'passion fruit': 'Fruit',
    'pomegranate': 'Fruit',
    'starfruit': 'Fruit',
    'tangerine': 'Fruit',
    'beet': 'Vegetable',
    'brussels sprout': 'Vegetable',
    'butternut squash': 'Vegetable',
    'fennel': 'Vegetable',
    'green bean': 'Vegetable',
    'leek': 'Vegetable',
    'okra': 'Vegetable',
    'parsnip': 'Vegetable',
    'radish': 'Vegetable',
    'rutabaga': 'Vegetable',
    'turnip': 'Vegetable',
    'artichoke': 'Vegetable',
    'asparagus': 'Vegetable',
    'bok choy': 'Vegetable',
    'collard greens': 'Vegetable',
    'endive': 'Vegetable',
    'escarole': 'Vegetable',
    'mustard greens': 'Vegetable',
    'snap pea': 'Vegetable',
    'swiss chard': 'Vegetable',
    'watercress': 'Vegetable',
    'alfalfa': 'Vegetable',
    'amaranth': 'Grain',
    'buckwheat': 'Grain',
    'bulgur': 'Grain',
    'farro': 'Grain',
    'kamut': 'Grain',
    'millet': 'Grain',
    'rye': 'Grain',
    'sorghum': 'Grain',
    'teff': 'Grain',
    'spelt': 'Grain',
    'ghee': 'Dairy',
    'gelato': 'Dairy',
    'ricotta': 'Dairy',
    'cottage cheese': 'Dairy',
    'brie': 'Dairy',
    'gouda': 'Dairy',
    'mozzarella': 'Dairy',
    'cheddar': 'Dairy',
    'swiss cheese': 'Dairy',
    'feta': 'Dairy',
    'camembert': 'Dairy',
    'parmesan': 'Dairy',
    'roquefort': 'Dairy',
    'pecorino': 'Dairy',
    'monterey jack': 'Dairy',
    'blue cheese': 'Dairy',
    'stilton': 'Dairy',
    'asiago': 'Dairy',
    'colby': 'Dairy',
    'provolone': 'Dairy',
    'havarti': 'Dairy',
    'manchego': 'Dairy',
    'fontina': 'Dairy',
    'muenster': 'Dairy',
    'romano': 'Dairy',
    'cotija': 'Dairy',
    'paneer': 'Dairy',
    'mascarpone': 'Dairy',
    'quark': 'Dairy',
    'halloumi': 'Dairy',
    'pecorino romano': 'Dairy',
    'carne asada': 'Meat',
    'chorizo': 'Meat',
    'corned beef': 'Meat',
    'duck confit': 'Meat',
    'goat': 'Meat',
    'ground beef': 'Meat',
    'ground pork': 'Meat',
    'kielbasa': 'Meat',
    'liverwurst': 'Meat',
    'mortadella': 'Meat',
    'pastrami': 'Meat',
    'prosciutto': 'Meat',
    'venison': 'Meat',
    'anchovy': 'Seafood',
    'calamari': 'Seafood',
    'caviar': 'Seafood',
    'eel': 'Seafood',
    'haddock': 'Seafood',
    'herring': 'Seafood',
    'mackerel': 'Seafood',
    'marlin': 'Seafood',
    'mussels': 'Seafood',
    'octopus': 'Seafood',
    'pollock': 'Seafood',
    'sardine': 'Seafood',
    'snapper': 'Seafood',
    'swordfish': 'Seafood',
    'tilapia': 'Seafood',
    'seaweed': 'Seafood',
    'kombu': 'Seafood',
    'wakame': 'Seafood',
    'nori': 'Seafood',
    'arame': 'Seafood',
    'agar': 'Seafood',
    'dulse': 'Seafood',
    'spirulina': 'Seafood',
    'chlorella': 'Seafood',
    'agar agar': 'Seafood',
    'salmon roe': 'Seafood',
    'flying fish roe': 'Seafood',
    'lobster roe': 'Seafood',
    'tomato paste': 'Condiment',
    'tomato sauce': 'Condiment',
    'sriracha': 'Condiment',
    'tahini': 'Condiment',
    'fish sauce': 'Condiment',
    'hoisin sauce': 'Condiment',
    'barbecue sauce': 'Condiment',
    'ranch dressing': 'Condiment',
    'italian dressing': 'Condiment',
    'blue cheese dressing': 'Condiment',
    'sesame oil': 'Condiment',
    'truffle oil': 'Condiment',
    'coconut oil': 'Condiment',
    'canola oil': 'Condiment',
    'vegetable oil': 'Condiment',
    'avocado oil': 'Condiment',
    'shortening': 'Condiment',
    'lard': 'Condiment',
    'crisco': 'Condiment',
    'peanut oil': 'Condiment',
    'grapeseed oil': 'Condiment',
    'safflower oil': 'Condiment',
    'sunflower oil': 'Condiment',
    'hemp oil': 'Condiment',
    'flaxseed oil': 'Condiment',
    'almond oil': 'Condiment',
    'walnut oil': 'Condiment',
    'pistachio oil': 'Condiment',
    'pumpkin seed oil': 'Condiment',
    'baking powder': 'Baking',
    'baking soda': 'Baking',
    'yeast': 'Baking',
    'cornstarch': 'Baking',
    'gelatin': 'Baking',
    'pectin': 'Baking',
    'cream of tartar': 'Baking',
    'agar powder': 'Baking',
    'xanthan gum': 'Baking',
    'guar gum': 'Baking',
    'arrowroot': 'Baking',
    'tapioca starch': 'Baking',
    'potato starch': 'Baking',
    'gluten': 'Baking',
    'vital wheat gluten': 'Baking',
    'malt': 'Baking',
    'malt syrup': 'Baking',
    'malt powder': 'Baking',
    'nonfat dry milk': 'Baking',
    'dried egg whites': 'Baking',
    'cocoa powder': 'Baking',
    'carob powder': 'Baking',
    'chocolate chips': 'Baking',
    'white chocolate chips': 'Baking',
    'butterscotch chips': 'Baking',
    'peanut butter chips': 'Baking',
    'cinnamon chips': 'Baking',
    'margarine': 'Baking',
    'unsalted butter': 'Baking',
    'salted butter': 'Baking',
    'buttermilk': 'Baking',
    'evaporated milk': 'Baking',
    'condensed milk': 'Baking',
    'dry milk powder': 'Baking',
    'whole wheat flour': 'Baking',
    'all-purpose flour': 'Baking',
    'bread flour': 'Baking',
    'cake flour': 'Baking',
    'pastry flour': 'Baking',
    'self-rising flour': 'Baking',
    'rice flour': 'Baking',
    'almond flour': 'Baking',
    'coconut flour': 'Baking',
    'soy flour': 'Baking',
    'oat flour': 'Baking',
    'teff flour': 'Baking',
    'spelt flour': 'Baking',
    'tapioca flour': 'Baking',
    'buckwheat flour': 'Baking',
    'cornmeal': 'Baking',
    'corn flour': 'Baking',
    'polenta': 'Baking',
    'corn grits': 'Baking',
    'masa harina': 'Baking',
    'semolina': 'Baking',
    'barley flour': 'Baking',
    'quinoa flour': 'Baking',
    'millet flour': 'Baking',
    'sorghum flour': 'Baking',
    'tiger nut flour': 'Baking',
    'chestnut flour': 'Baking',
    'hazelnut flour': 'Baking',
    'peanut flour': 'Baking',
    'pumpkin flour': 'Baking',
    'sunflower seed flour': 'Baking',
    'flaxseed meal': 'Baking',
    'hemp flour': 'Baking',
    'chia flour': 'Baking',
    'cassava flour': 'Baking',
    'plantain flour': 'Baking',
    'cricket flour': 'Baking',
    'black bean flour': 'Baking',
    'garbanzo bean flour': 'Baking',
    'green pea flour': 'Baking',
    'fava bean flour': 'Baking',
    'red lentil flour': 'Baking',
    'yellow lentil flour': 'Baking',
    'urad dal flour': 'Baking',
    'moong dal flour': 'Baking',
    'mung bean flour': 'Baking',
    'adzuki bean flour': 'Baking',
    'curry powder': 'Spice',
    'paprika': 'Spice',
    'cayenne pepper': 'Spice',
    'chili powder': 'Spice',
    'ground cumin': 'Spice',
    'ground coriander': 'Spice',
    'ground cardamom': 'Spice',
    'ground cloves': 'Spice',
    'ground allspice': 'Spice',
    'ground mustard': 'Spice',
    'ground ginger': 'Spice',
    'ground nutmeg': 'Spice',
    'ground turmeric': 'Spice',
    'ground cinnamon': 'Spice',
    'garam masala': 'Spice',
    'fennel seeds': 'Spice',
    'fenugreek seeds': 'Spice',
    'coriander seeds': 'Spice',
    'caraway seeds': 'Spice',
    'dill seeds': 'Spice',
    'nigella seeds': 'Spice',
    'anise seeds': 'Spice',
    'celery seeds': 'Spice',
    'poppy seeds': 'Spice',
    'sesame seeds': 'Spice',
    'mustard seeds': 'Spice',
    'juniper berries': 'Spice',
    'szechuan peppercorns': 'Spice',
    'black peppercorns': 'Spice',
    'white peppercorns': 'Spice',
    'pink peppercorns': 'Spice',
    'green peppercorns': 'Spice',
    'star anise': 'Spice',
    'cinnamon sticks': 'Spice',
    'cloves': 'Spice',
    'bay leaves': 'Spice',
    'vanilla beans': 'Spice',
    'saffron': 'Spice',
    'turmeric root': 'Spice',
    'ginger root': 'Spice',
    'galangal root': 'Spice',
    'lemongrass': 'Herb',
    'parsley': 'Herb',
    'cilantro': 'Herb',
    'rosemary': 'Herb',
    'thyme': 'Herb',
    'oregano': 'Herb',
    'mint': 'Herb',
    'basil': 'Herb',
    'sage': 'Herb',
    'marjoram': 'Herb',
    'dill': 'Herb',
    'tarragon': 'Herb',
    'chervil': 'Herb',
    'chives': 'Herb',
    'fennel fronds': 'Herb',
    'bay leaves': 'Herb',
    'lavender': 'Herb',
    'lemon balm': 'Herb',
    'savory': 'Herb',
    'sorrel': 'Herb',
    'watercress': 'Herb',
    'nasturtium': 'Herb',
    'lovage': 'Herb',
    'borage': 'Herb',
    'burnet': 'Herb',
    'sweet cicely': 'Herb',
    'winter savory': 'Herb',
    'summer savory': 'Herb',
    'hyssop': 'Herb',
    'anise hyssop': 'Herb',
    'bergamot': 'Herb',
    'culantro': 'Herb',
    'shiso': 'Herb',
    'perilla': 'Herb',
    'hoja santa': 'Herb',
    'lemon verbena': 'Herb',
    'stevia': 'Herb',
    'feverfew': 'Herb',
    'goldenrod': 'Herb',
    'horehound': 'Herb',
    'meadowsweet': 'Herb',
    'motherwort': 'Herb',
    'woodruff': 'Herb',
    'angelica': 'Herb',
    'celandine': 'Herb',
    'echinacea': 'Herb',
    'fennel seeds': 'Herb',
    'horehound': 'Herb',
    'lemon balm': 'Herb',
    'marshmallow': 'Herb',
    'red clover': 'Herb'
}

