# Generated by Django 5.0.4 on 2024-04-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0002_remove_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
