# Generated by Django 5.0.4 on 2024-04-25 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('l', 'Litri'), ('g', 'Grammi'), ('u', 'Unità')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='unit_of_measure',
            field=models.CharField(choices=[('l', 'Litri'), ('g', 'Grammi'), ('u', 'Unità')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
