# Generated by Django 5.0.4 on 2024-05-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0005_product_unit_of_measure_shoppinglist_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('L', 'Litri'), ('g', 'Grammi'), ('u', 'Unità')], max_length=1),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='unit_of_measure',
            field=models.CharField(choices=[('L', 'Litri'), ('g', 'Grammi'), ('u', 'Unità')], max_length=1),
        ),
    ]
