# Generated by Django 5.0.4 on 2024-05-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0006_alter_product_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='always_in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
