# Generated by Django 5.0.4 on 2024-05-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0007_shoppinglist_always_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
