# Generated by Django 5.0.4 on 2024-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0009_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
