# Generated by Django 5.0.4 on 2024-05-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0011_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='immagine',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='nome',
            new_name='name',
        ),
    ]
