# Generated by Django 5.0.4 on 2024-05-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0012_rename_immagine_about_image_rename_nome_about_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='occupation',
            field=models.CharField(default='', max_length=30),
        ),
    ]
