# Generated by Django 5.0.4 on 2024-05-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0013_about_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='developerNum',
            field=models.FloatField(default=0),
        ),
    ]
