# Generated by Django 5.0.4 on 2024-05-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0014_about_developernum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='Developer',
        ),
    ]
