# Generated by Django 5.0.4 on 2024-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack', '0015_rename_about_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developerNum',
            field=models.IntegerField(),
        ),
    ]
