name: Django CI

on:
  push:
    branches: [ main ]  # Esegui il workflow quando si effettua il push sul branch principale
  pull_request:
    branches: [ main ]  # Esegui il workflow quando viene aperta una pull request verso il branch principale

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations and tests
        run: |
          python manage.py migrate
          python manage.py test

